version: '3'

services:
  artemis:
    image: vromero/activemq-artemis:2.13.0-alpine
    ports:
      - "61040:61613"
    environment:
      - DISABLE_SECURITY=true
    volumes:
      - ./travisci/conf/artemis/broker-00.xml:/var/lib/artemis/etc-override/broker-00.xml:ro

  active-mq:
    image: rmohr/activemq:5.14.5-alpine
    ports:
      - "61010:61010"
    volumes:
      - ./travisci/conf/amq/activemq.xml:/opt/activemq/conf/activemq.xml

  rabbit-mq:
    image: rabbitmq:3.6.11
    ports:
      - "61030:61030"
    volumes:
      - ./travisci/conf/rabbit/:/etc/rabbitmq/

  apollo-mq:
    image: finsn/stomp-apollo:1.7.1
    ports:
      - "61020:61020"
