name: CI
on: [pull_request]
jobs:
  static_analysis:
    name: Static analysis with phpstan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'

      - run: composer require --dev phpstan/phpstan

      - run: vendor/bin/phpstan analyse

  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['5.6', '7.0', '7.1', '7.2', '7.3']
    name: PHP ${{ matrix.php }} tests
    steps:
      - uses: actions/checkout@v2

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - uses: shivammathur/setup-php@v2
        with:
          php-version: matrix.php
          coverage: xdebug

      - run: ./travisci/bin/start.sh

      - run: composer install --no-progress

      - run: ./travisci/bin/logs.sh
