name: CI
on: [pull_request]
jobs:
  static_analysis:
    name: Static analysis with phpstan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'

      - uses: "ramsey/composer-install@v1"

      - run: composer require --dev phpstan/phpstan

      - run: vendor/bin/phpstan analyse

  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['5.6', '7.0', '7.1', '7.2', '7.3']
    name: PHP ${{ matrix.php }} tests
    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - run: docker-compose up -d

      - uses: nev7n/wait_for_response@v1
        with:
          url: 'http://127.0.0.1:61010/admin'
          responseCode: 200
          timeout: 50000
          interval: 1000

      - uses: "ramsey/composer-install@v1"

      - run: docker-compose logs -f &

      - run: vendor/bin/phpunit

      - run: docker-compose down
